window.PR_SHOULD_USE_CONTINUATION=!0;var prettyPrintOne,prettyPrint;
(function(){function N(a){function h(d){var a=d.charCodeAt(0);if(a!==92)return a;var f=d.charAt(1);return(a=r[f])?a:"0"<=f&&f<="7"?parseInt(d.substring(1),8):f==="u"||f==="x"?parseInt(d.substring(2),16):d.charCodeAt(1)}function i(d){if(d<32)return(d<16?"\\x0":"\\x")+d.toString(16);d=String.fromCharCode(d);return d==="\\"||d==="-"||d==="]"||d==="^"?"\\"+d:d}function j(d){var a=d.substring(1,d.length-1).match(/\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\S\s]|[^\\]/g),d=[],f=
a[0]==="^",b=["["];f&&b.push("^");for(var f=f?1:0,c=a.length;f<c;++f){var g=a[f];if(/\\[bdsw]/i.test(g))b.push(g);else{var g=h(g),e;f+2<c&&"-"===a[f+1]?(e=h(a[f+2]),f+=2):e=g;d.push([g,e]);e<65||g>122||(e<65||g>90||d.push([Math.max(65,g)|32,Math.min(e,90)|32]),e<97||g>122||d.push([Math.max(97,g)&-33,Math.min(e,122)&-33]))}}d.sort(function(d,a){return d[0]-a[0]||a[1]-d[1]});a=[];c=[];for(f=0;f<d.length;++f)g=d[f],g[0]<=c[1]+1?c[1]=Math.max(c[1],g[1]):a.push(c=g);for(f=0;f<a.length;++f)g=a[f],b.push(i(g[0])),
g[1]>g[0]&&(g[1]+1>g[0]&&b.push("-"),b.push(i(g[1])));b.push("]");return b.join("")}function v(d){for(var a=d.source.match(/\[(?:[^\\\]]|\\[\S\s])*]|\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\\d+|\\[^\dux]|\(\?[!:=]|[()^]|[^()[\\^]+/g),b=a.length,h=[],c=0,g=0;c<b;++c){var e=a[c];e==="("?++g:"\\"===e.charAt(0)&&(e=+e.substring(1))&&(e<=g?h[e]=-1:a[c]=i(e))}for(c=1;c<h.length;++c)-1===h[c]&&(h[c]=++p);for(g=c=0;c<b;++c)e=a[c],e==="("?(++g,h[g]||(a[c]="(?:")):"\\"===e.charAt(0)&&(e=+e.substring(1))&&e<=g&&
(a[c]="\\"+h[e]);for(c=0;c<b;++c)"^"===a[c]&&"^"!==a[c+1]&&(a[c]="");if(d.ignoreCase&&s)for(c=0;c<b;++c)e=a[c],d=e.charAt(0),e.length>=2&&d==="["?a[c]=j(e):d!=="\\"&&(a[c]=e.replace(/[A-Za-z]/g,function(d){d=d.charCodeAt(0);return"["+String.fromCharCode(d&-33,d|32)+"]"}));return a.join("")}for(var p=0,s=!1,k=!1,l=0,b=a.length;l<b;++l){var m=a[l];if(m.ignoreCase)k=!0;else if(/[a-z]/i.test(m.source.replace(/\\u[\da-f]{4}|\\x[\da-f]{2}|\\[^UXux]/gi,""))){s=!0;k=!1;break}}for(var r={b:8,t:9,n:10,v:11,
f:12,r:13},q=[],l=0,b=a.length;l<b;++l){m=a[l];if(m.global||m.multiline)throw Error(""+m);q.push("(?:"+v(m)+")")}return RegExp(q.join("|"),k?"gi":"g")}function O(a,h){function i(a){switch(a.nodeType){case 1:if(j.test(a.className))break;for(var b=a.firstChild;b;b=b.nextSibling)i(b);b=a.nodeName.toLowerCase();if("br"===b||"li"===b)v[k]="\n",s[k<<1]=p++,s[k++<<1|1]=a;break;case 3:case 4:b=a.nodeValue,b.length&&(b=h?b.replace(/\r\n?/g,"\n"):b.replace(/[\t\n\r ]+/g," "),v[k]=b,s[k<<1]=p,p+=b.length,s[k++<<
1|1]=a)}}var j=/(?:^|\s)nocode(?:\s|$)/,v=[],p=0,s=[],k=0;i(a);return{sourceCode:v.join("").replace(/\n$/,""),spans:s}}function D(a,h,i,j){h&&(a={sourceCode:h,basePos:a},i(a),j.push.apply(j,a.decorations))}function w(a,h){var i={},j;(function(){for(var s=a.concat(h),k=[],l={},b=0,m=s.length;b<m;++b){var r=s[b],q=r[3];if(q)for(var d=q.length;--d>=0;)i[q.charAt(d)]=r;r=r[1];q=""+r;l.hasOwnProperty(q)||(k.push(r),l[q]=null)}k.push(/[\S\s]/);j=N(k)})();var v=h.length,p=function(a){for(var k=a.basePos,
l=[k,"pln"],b=0,m=a.sourceCode.match(j)||[],r={},q=0,d=m.length;q<d;++q){var x=m[q],f=r[x],u=void 0,c;if(typeof f==="string")c=!1;else{var g=i[x.charAt(0)];if(g)u=x.match(g[1]),f=g[0];else{for(c=0;c<v;++c)if(g=h[c],u=x.match(g[1])){f=g[0];break}u||(f="pln")}if((c=f.length>=5&&"lang-"===f.substring(0,5))&&!(u&&typeof u[1]==="string"))c=!1,f="src";c||(r[x]=f)}g=b;b+=x.length;if(c){c=u[1];var e=x.indexOf(c),o=e+c.length;u[2]&&(o=x.length-u[2].length,e=o-c.length);f=f.substring(5);D(k+g,x.substring(0,
e),p,l);D(k+g+e,c,E(f,c),l);D(k+g+o,x.substring(o),p,l)}else l.push(k+g,f)}a.decorations=l};return p}function n(a){var h=[],i=[];a.tripleQuotedStrings?h.push(["str",/^(?:'''(?:[^'\\]|\\[\S\s]|''?(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\S\s]|""?(?=[^"]))*(?:"""|$)|'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$))/,null,"'\""]):a.multiLineStrings?h.push(["str",/^(?:'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$)|`(?:[^\\`]|\\[\S\s])*(?:`|$))/,null,"'\"`"]):h.push(["str",/^(?:'(?:[^\n\r'\\]|\\.)*(?:'|$)|"(?:[^\n\r"\\]|\\.)*(?:"|$))/,
null,"\"'"]);a.verbatimStrings&&i.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var j=a.hashComments;j&&(a.cStyleComments?(j>1?h.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):h.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\n\r]*)/,null,"#"]),i.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,null])):h.push(["com",/^#[^\n\r]*/,null,"#"]));a.cStyleComments&&(i.push(["com",/^\/\/[^\n\r]*/,
null]),i.push(["com",/^\/\*[\S\s]*?(?:\*\/|$)/,null]));a.regexLiterals&&i.push(["lang-regex",/^(?:^^\.?|[+-]|[!=]={0,2}|#|%=?|&&?=?|\(|\*=?|[+-]=|->|\/=?|::?|<<?=?|>{1,3}=?|[,;?@[{~]|\^\^?=?|\|\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\s*(\/(?=[^*/])(?:[^/[\\]|\\[\S\s]|\[(?:[^\\\]]|\\[\S\s])*(?:]|$))+\/)/]);(j=a.types)&&i.push(["typ",j]);a=(""+a.keywords).replace(/^ | $/g,"");a.length&&i.push(["kwd",RegExp("^(?:"+a.replace(/[\s,]+/g,"|")+")\\b"),null]);h.push(["pln",
/^\s+/,null," \r\n\t\u00a0"]);i.push(["lit",/^@[$_a-z][\w$@]*/i,null],["typ",/^(?:[@_]?[A-Z]+[a-z][\w$@]*|\w+_t\b)/,null],["pln",/^[$_a-z][\w$@]*/i,null],["lit",/^(?:0x[\da-f]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+-]?\d+)?)[a-z]*/i,null,"0123456789"],["pln",/^\\[\S\s]?/,null],["pun",/^.[^\s\w"$'./@\\`]*/,null]);return w(h,i)}function F(a,h,i){function j(a){switch(a.nodeType){case 1:if(p.test(a.className))break;if("br"===a.nodeName)v(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=
a.nextSibling)j(a);break;case 3:case 4:if(i){var b=a.nodeValue,f=b.match(s);if(f){var h=b.substring(0,f.index);a.nodeValue=h;(b=b.substring(f.index+f[0].length))&&a.parentNode.insertBefore(k.createTextNode(b),a.nextSibling);v(a);h||a.parentNode.removeChild(a)}}}}function v(a){function h(a,b){var d=b?a.cloneNode(!1):a,e=a.parentNode;if(e){var e=h(e,1),f=a.nextSibling;e.appendChild(d);for(var i=f;i;i=f)f=i.nextSibling,e.appendChild(i)}return d}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;for(var a=
h(a.nextSibling,0),f;(f=a.parentNode)&&f.nodeType===1;)a=f;b.push(a)}for(var p=/(?:^|\s)nocode(?:\s|$)/,s=/\r\n?|\n/,k=a.ownerDocument,l=k.createElement("li");a.firstChild;)l.appendChild(a.firstChild);for(var b=[l],m=0;m<b.length;++m)j(b[m]);h===(h|0)&&b[0].setAttribute("value",h);var r=k.createElement("ol");r.className="linenums";for(var h=Math.max(0,h-1|0)||0,m=0,q=b.length;m<q;++m)l=b[m],l.className="L"+(m+h)%10,l.firstChild||l.appendChild(k.createTextNode("\u00a0")),r.appendChild(l);a.appendChild(r)}
function t(a,h){for(var i=h.length;--i>=0;){var j=h[i];z.hasOwnProperty(j)?B.console&&console.warn("cannot override language handler %s",j):z[j]=a}}function E(a,h){if(!a||!z.hasOwnProperty(a))a=/^\s*</.test(h)?"default-markup":"default-code";return z[a]}function G(a){var h=a.langExtension;try{var i=O(a.sourceNode,a.pre),j=i.sourceCode;a.sourceCode=j;a.spans=i.spans;a.basePos=0;E(h,j)(a);var v=/\bMSIE\s(\d+)/.exec(navigator.userAgent),v=v&&+v[1]<=8,h=/\n/g,p=a.sourceCode,s=p.length,i=0,k=a.spans,l=
k.length,j=0,b=a.decorations,m=b.length,r=0;b[m]=s;var q,d;for(d=q=0;d<m;)b[d]!==b[d+2]?(b[q++]=b[d++],b[q++]=b[d++]):d+=2;m=q;for(d=q=0;d<m;){for(var t=b[d],f=b[d+1],u=d+2;u+2<=m&&b[u+1]===f;)u+=2;b[q++]=t;b[q++]=f;d=u}b.length=q;var c=a.sourceNode,g;if(c)g=c.style.display,c.style.display="none";try{for(;j<l;){var e=k[j+2]||s,o=b[r+2]||s,u=Math.min(e,o),n=k[j+1],C;if(n.nodeType!==1&&(C=p.substring(i,u))){v&&(C=C.replace(h,"\r"));n.nodeValue=C;var y=n.ownerDocument,w=y.createElement("span");w.className=
b[r+1];var A=n.parentNode;A.replaceChild(w,n);w.appendChild(n);i<e&&(k[j+1]=n=y.createTextNode(p.substring(u,e)),A.insertBefore(n,w.nextSibling))}i=u;i>=e&&(j+=2);i>=o&&(r+=2)}}finally{if(c)c.style.display=g}}catch(z){B.console&&console.log(z&&z.stack?z.stack:z)}}var B=window,y=["break,continue,do,else,for,if,return,while"],A=[[y,"auto,case,char,const,default,double,enum,extern,float,goto,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],
H=[A,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,dynamic_cast,explicit,export,friend,inline,late_check,mutable,namespace,nullptr,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],I=[A,"abstract,boolean,byte,extends,final,finally,implements,import,instanceof,null,native,package,strictfp,super,synchronized,throws,transient"],J=[I,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,interface,internal,into,is,let,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var,virtual,where"],
A=[A,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"],K=[y,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],L=[y,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],y=[y,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],M=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,
P=/\S/,Q=n({keywords:[H,J,A,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END"+K,L,y],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),z={};t(Q,["default-code"]);t(w([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\S\s]*?(?:--\>|$)/],["lang-",/^<\?([\S\s]+?)(?:\?>|$)/],["lang-",/^<%([\S\s]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",
/^<xmp\b[^>]*>([\S\s]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\S\s]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\S\s]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),["default-markup","htm","html","mxml","xhtml","xml","xsl"]);t(w([["pln",/^\s+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w-.:]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^\s"'>]*(?:[^\s"'/>]|\/(?=\s)))/],["pun",
/^[/<->]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^\s"'>]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",/^style\s*=\s*([^\s"'>]+)/i]]),["in.tag"]);t(w([],[["atv",/^[\S\s]+/]]),["uq.val"]);t(n({keywords:H,hashComments:!0,cStyleComments:!0,types:M}),["c","cc","cpp","cxx","cyc","m"]);t(n({keywords:"null,true,false"}),["json"]);t(n({keywords:J,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,
types:M}),["cs"]);t(n({keywords:I,cStyleComments:!0}),["java"]);t(n({keywords:y,hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);t(n({keywords:K,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);t(n({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);t(n({keywords:L,
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);t(n({keywords:A,cStyleComments:!0,regexLiterals:!0}),["js"]);t(n({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);t(w([],[["str",/^[\S\s]+/]]),["regex"]);var R=B.PR={createSimpleLexer:w,registerLangHandler:t,
sourceDecorator:n,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:B.prettyPrintOne=function(a,h,i){var j=document.createElement("pre");j.innerHTML=a;i&&F(j,i,!0);G({langExtension:h,numberLines:i,sourceNode:j,pre:1});return j.innerHTML},prettyPrint:B.prettyPrint=function(a){function h(){var u;for(var i=B.PR_SHOULD_USE_CONTINUATION?
k.now()+250:Infinity;l<j.length&&k.now()<i;l++){var c=j[l],g=c.className;if(r.test(g)&&!q.test(g)){for(var e=!1,o=c.parentNode;o;o=o.parentNode)if(f.test(o.tagName)&&o.className&&r.test(o.className)){e=!0;break}if(!e){c.className+=" prettyprinted";var g=g.match(m),n;if(e=!g){for(var e=c,o=void 0,p=e.firstChild;p;p=p.nextSibling)var s=p.nodeType,o=s===1?o?e:p:s===3?P.test(p.nodeValue)?e:o:o;e=(n=o===e?void 0:o)&&t.test(n.tagName)}e&&(g=n.className.match(m));g&&(g=g[1]);u=d.test(c.tagName)?1:(e=(e=
c.currentStyle)?e.whiteSpace:document.defaultView&&document.defaultView.getComputedStyle?document.defaultView.getComputedStyle(c,null).getPropertyValue("white-space"):0)&&"pre"===e.substring(0,3),e=u;(o=(o=c.className.match(/\blinenums\b(?::(\d+))?/))?o[1]&&o[1].length?+o[1]:!0:!1)&&F(c,o,e);b={langExtension:g,sourceNode:c,numberLines:o,pre:e};G(b)}}}l<j.length?setTimeout(h,250):a&&a()}for(var i=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],
j=[],n=0;n<i.length;++n)for(var p=0,s=i[n].length;p<s;++p)j.push(i[n][p]);var i=null,k=Date;k.now||(k={now:function(){return+new Date}});var l=0,b,m=/\blang(?:uage)?-([\w.]+)(?!\S)/,r=/\bprettyprint\b/,q=/\bprettyprinted\b/,d=/pre|xmp/i,t=/^code$/i,f=/^(?:pre|code|xmp)$/i;h()}};typeof define==="function"&&define.amd&&define("google-code-prettify",[],function(){return R})})();
