// 
// Code generated by Identity and Access VS Package
// 

function ShowSigninPage(IPs) {
    $.each(IPs, function (i, ip) {
        $("#IPDiv").append('<a href="' + ip.LoginUrl + '">' + ip.Name + '</a><br/>');
    });
};
