// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System.Diagnostics;
using System.CodeDom.Compiler;

namespace FunnelWeb.Web {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string Markdown = "~/Views/Shared/DisplayTemplates/Markdown.ascx";
            }
            static readonly _Images s_Images = new _Images();
            public _Images Images { get { return s_Images; } }
            public partial class _Images{
                public readonly string editorbuttons = "~/Views/Shared/Images/editorbuttons.png";
                public readonly string external = "~/Views/Shared/Images/external.png";
                public readonly string favicon = "~/Views/Shared/Images/favicon.ico";
                public readonly string title = "~/Views/Shared/Images/title.png";
                public readonly string transparent = "~/Views/Shared/Images/transparent.gif";
                static readonly _FileTypes s_FileTypes = new _FileTypes();
                public _FileTypes FileTypes { get { return s_FileTypes; } }
                public partial class _FileTypes{
                    public readonly string bmp = "~/Views/Shared/Images/FileTypes/bmp.png";
                    public readonly string cs = "~/Views/Shared/Images/FileTypes/cs.png";
                    public readonly string csproj = "~/Views/Shared/Images/FileTypes/csproj.png";
                    public readonly string @default = "~/Views/Shared/Images/FileTypes/default.png";
                    public readonly string dir = "~/Views/Shared/Images/FileTypes/dir.png";
                    public readonly string doc = "~/Views/Shared/Images/FileTypes/doc.png";
                    public readonly string Document = "~/Views/Shared/Images/FileTypes/Document.png";
                    public readonly string docx = "~/Views/Shared/Images/FileTypes/docx.png";
                    public readonly string gif = "~/Views/Shared/Images/FileTypes/gif.png";
                    public readonly string Installer = "~/Views/Shared/Images/FileTypes/Installer.png";
                    public readonly string jpg = "~/Views/Shared/Images/FileTypes/jpg.png";
                    public readonly string Link = "~/Views/Shared/Images/FileTypes/Link.png";
                    public readonly string png = "~/Views/Shared/Images/FileTypes/png.png";
                    public readonly string pps = "~/Views/Shared/Images/FileTypes/pps.png";
                    public readonly string ppsx = "~/Views/Shared/Images/FileTypes/ppsx.png";
                    public readonly string ppt = "~/Views/Shared/Images/FileTypes/ppt.png";
                    public readonly string pptx = "~/Views/Shared/Images/FileTypes/pptx.png";
                    public readonly string rar = "~/Views/Shared/Images/FileTypes/rar.png";
                    public readonly string sln = "~/Views/Shared/Images/FileTypes/sln.png";
                    public readonly string tar = "~/Views/Shared/Images/FileTypes/tar.png";
                    public readonly string xls = "~/Views/Shared/Images/FileTypes/xls.png";
                    public readonly string xlsx = "~/Views/Shared/Images/FileTypes/xlsx.png";
                    public readonly string Zip = "~/Views/Shared/Images/FileTypes/Zip.png";
                }
            }
            static readonly _Resources s_Resources = new _Resources();
            public _Resources Resources { get { return s_Resources; } }
            public partial class _Resources{
                public readonly string favicon = "~/Views/Shared/Resources/favicon.ico";
                public readonly string favicon_png = "~/Views/Shared/Resources/favicon.png";
                public readonly string Robots = "~/Views/Shared/Resources/Robots.txt";
                public readonly string Status = "~/Views/Shared/Resources/Status.html";
            }
            static readonly _Scripts s_Scripts = new _Scripts();
            public _Scripts Scripts { get { return s_Scripts; } }
            public partial class _Scripts{
                static readonly _JQuery s_JQuery = new _JQuery();
                public _JQuery JQuery { get { return s_JQuery; } }
                public partial class _JQuery{
                    public readonly string jquery_1_3_2_vsdoc = "~/Views/Shared/Scripts/JQuery/jquery-1.3.2-vsdoc.js";
                    public readonly string jquery_1_3_2 = "~/Views/Shared/Scripts/JQuery/jquery-1.3.2.js";
                    public readonly string jquery_1_3_2_min_vsdoc = "~/Views/Shared/Scripts/JQuery/jquery-1.3.2.min-vsdoc.js";
                    public readonly string jquery_1_3_2_min = "~/Views/Shared/Scripts/JQuery/jquery-1.3.2.min.js";
                    public readonly string jquery_fieldselection = "~/Views/Shared/Scripts/JQuery/jquery-fieldselection.js";
                    public readonly string jquery_scrollto = "~/Views/Shared/Scripts/JQuery/jquery-scrollto.js";
                    public readonly string jquery_ui_1_7_3_custom = "~/Views/Shared/Scripts/JQuery/jquery-ui-1.7.3.custom.css";
                    public readonly string jquery_ui_1_7_3_custom_min = "~/Views/Shared/Scripts/JQuery/jquery-ui-1.7.3.custom.min.js";
                    public readonly string jquery_validation = "~/Views/Shared/Scripts/JQuery/jquery-validation.js";
                    public readonly string jsdate = "~/Views/Shared/Scripts/JQuery/jsdate.js";
                    static readonly _images s_images = new _images();
                    public _images images { get { return s_images; } }
                    public partial class _images{
                        public readonly string ui_bg_diagonals_thick_18_b81900_40x40 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_diagonals-thick_18_b81900_40x40.png";
                        public readonly string ui_bg_diagonals_thick_20_666666_40x40 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_diagonals-thick_20_666666_40x40.png";
                        public readonly string ui_bg_flat_10_000000_40x100 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_flat_10_000000_40x100.png";
                        public readonly string ui_bg_glass_100_f6f6f6_1x400 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_glass_100_f6f6f6_1x400.png";
                        public readonly string ui_bg_glass_100_fdf5ce_1x400 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_glass_100_fdf5ce_1x400.png";
                        public readonly string ui_bg_glass_65_ffffff_1x400 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_glass_65_ffffff_1x400.png";
                        public readonly string ui_bg_gloss_wave_35_f6a828_500x100 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_gloss-wave_35_f6a828_500x100.png";
                        public readonly string ui_bg_highlight_soft_100_eeeeee_1x100 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_highlight-soft_100_eeeeee_1x100.png";
                        public readonly string ui_bg_highlight_soft_75_ffe45c_1x100 = "~/Views/Shared/Scripts/JQuery/images/ui-bg_highlight-soft_75_ffe45c_1x100.png";
                        public readonly string ui_icons_222222_256x240 = "~/Views/Shared/Scripts/JQuery/images/ui-icons_222222_256x240.png";
                        public readonly string ui_icons_228ef1_256x240 = "~/Views/Shared/Scripts/JQuery/images/ui-icons_228ef1_256x240.png";
                        public readonly string ui_icons_ef8c08_256x240 = "~/Views/Shared/Scripts/JQuery/images/ui-icons_ef8c08_256x240.png";
                        public readonly string ui_icons_ffd27a_256x240 = "~/Views/Shared/Scripts/JQuery/images/ui-icons_ffd27a_256x240.png";
                        public readonly string ui_icons_ffffff_256x240 = "~/Views/Shared/Scripts/JQuery/images/ui-icons_ffffff_256x240.png";
                    }
                }
                static readonly _MD5 s_MD5 = new _MD5();
                public _MD5 MD5 { get { return s_MD5; } }
                public partial class _MD5{
                    public readonly string MD5 = "~/Views/Shared/Scripts/MD5/MD5.js";
                }
                static readonly _Prettify s_Prettify = new _Prettify();
                public _Prettify Prettify { get { return s_Prettify; } }
                public partial class _Prettify{
                    public readonly string prettify = "~/Views/Shared/Scripts/Prettify/prettify.js";
                }
                static readonly _Showdown s_Showdown = new _Showdown();
                public _Showdown Showdown { get { return s_Showdown; } }
                public partial class _Showdown{
                    public readonly string showdown = "~/Views/Shared/Scripts/Showdown/showdown.js";
                    public readonly string wmd = "~/Views/Shared/Scripts/Showdown/wmd.js";
                }
                static readonly _Site s_Site = new _Site();
                public _Site Site { get { return s_Site; } }
                public partial class _Site{
                    public readonly string Site = "~/Views/Shared/Scripts/Site/Site.js";
                }
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
