// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System.CodeDom.Compiler;

namespace FunnelWeb.Web {
    [GeneratedCode("T4MVC", "2.0")]
    public static class HtmlHelpersForExplicitPartials {
    	 
    }
	
}
#endregion T4MVC
#pragma warning restore 1591
